### ISSUE TITLE
1.0.5 リリース

### ISSUE THREAD

**Issue by uehara1414** [uehara1414/japanize-matplotlib#5]
## TODO
- [x] HISTORY.md 作成
  - [x] @elnikkis さんの修正を追加
  - [x] README.md に反映
- [x] リリース
  - [x] setup.py 書き換え
- [x] Qiitaへ修正を追記
